/** User-requested Class A coverage. Checks and procedures are not physical meshes. */
export type InspectionItem={id:string;en:string;es:string;kind:'part'|'check'|'procedure';assembly?:string;focus:string;conditional?:string};
export type InspectionSection={id:string;name:string;en:string;items:InspectionItem[]};
const part=(id:string,en:string,es:string,focus:string,assembly?:string,conditional?:string):InspectionItem=>({id,en,es,focus,assembly,conditional,kind:'part'});
const check=(id:string,en:string,es:string,focus:string,assembly?:string):InspectionItem=>({id,en,es,focus,assembly,kind:'check'});
const procedure=(id:string,en:string,es:string,focus:string):InspectionItem=>({id,en,es,focus,kind:'procedure'});
export const targetVehicle={tractor:'Freightliner Cascadia · 126″ Day Cab',engine:'Detroit DD15 Gen 5',trailer:'Semirremolque seco de 53 pies',year:null,geometryVerified:false,description:'Reconstrucción basada en referencias oficiales de Cascadia y DD15. Remolque de 53 pies; equipos e instalación ilustrativos. No es CAD OEM ni una réplica 1:1 validada.'};
export const inspectionCatalog:InspectionSection[]=[
 {id:'in-cab',name:'Cabina y arranque',en:'In-cab / engine start',items:[
  procedure('air-brake-test','Air brake check','Prueba de frenos de aire','Demostrar el procedimiento completo y sus límites para el vehículo y el formato de examen; requiere controles, manómetros y señales operativas.'),
  procedure('tractor-parking-test','Parking / tractor brake','Freno de estacionamiento del tractor','Demostrar la retención del tractor según la secuencia segura del manual.'),
  procedure('trailer-parking-test','Trailer brake','Freno del remolque','Demostrar la retención del remolque y distinguirla del freno de estacionamiento del tractor.'),
  procedure('service-brake-test','Service brake','Freno de servicio','Demostrar detención y verificar que el vehículo no se desvíe siguiendo el procedimiento del manual.'),
  part('dash-indicators','Lighting indicators','Indicadores del tablero','Identificar y comprobar luces indicadoras, advertencias y secuencia de encendido.'),
  check('emergency-equipment','Emergency equipment','Equipo de emergencia','Localizar y comprobar el equipo exigido, incluidos triángulos, extintor y protección eléctrica.','safety'),
  part('triangles','3 reflective triangles','Tres triángulos reflectantes','Localización, cantidad y estado del equipo de señalización.'),
  part('fire-extinguisher','Fire extinguisher','Extintor','Sujeción, carga y condición.','safety'),
  part('fuses-breakers','Fuses / circuit breakers','Fusibles / disyuntores','Identificar el sistema instalado y los repuestos que correspondan.'),
  part('windshield','Windshield','Parabrisas','Limpieza, daños y obstrucciones de la visión.','mirrors'),
  part('cab-mirrors','Mirrors / traffic monitoring devices','Espejos / dispositivos de visión','Sujeción, limpieza, funcionamiento y ajuste desde la posición del conductor.','mirrors'),
  part('wipers','Wipers','Limpiaparabrisas','Estado de brazos y escobillas, sujeción y demostración de funcionamiento.','mirrors'),
  part('washer','Windshield washer','Lavaparabrisas','Depósito, líquido y demostración del rociado.'),
  part('heater','Heater','Calefacción','Ubicar el control y demostrar que funciona.'),
  part('defroster','Defroster','Desempañador','Ubicar el control y demostrar el flujo de aire hacia el parabrisas.'),
  part('horn','Horn','Bocina','Ubicar y probar las bocinas instaladas.'),
 ]},
 {id:'exterior-lights',name:'Luces exteriores',en:'External lights',items:[
  part('headlights','Headlights','Faros','Lentes, fijación y funcionamiento.','lights'),
  check('high-beams','High beams','Luces altas','Demostrar encendido y su indicador.','lights'),
  check('low-beams','Low beams','Luces bajas','Demostrar encendido de ambas luces.','lights'),
  check('turn-signals','Turn signals','Direccionales','Verificar señales de ambos lados.','lights'),
  check('hazard-lights','4-way flashers','Intermitentes de emergencia','Demostrar el funcionamiento simultáneo.','lights'),
  part('clearance-lights','Clearance / marker lights','Luces de gálibo / marcadoras','Posición, estado y funcionamiento.','lights'),
  part('tail-lights','Tail lights','Luces de posición traseras','Estado y encendido.','reflectors'),
  check('brake-lights','Brake lights','Luces de freno','Verificar que respondan a la aplicación y liberación del freno.','reflectors'),
  part('external-reflectors','Reflectors','Reflectores','Limpieza, presencia y condición.','reflectors'),
 ]},
 {id:'engine-area',name:'Frente y área del motor',en:'Front / engine area',items:[
  part('front-lenses','Lenses','Lentes delanteras','Color apropiado, limpieza, fijación y ausencia de roturas.','lights'),
  check('fluid-levels','Fluid levels','Niveles de líquidos','Identificar los puntos de comprobación y las marcas de cada depósito.'),
  check('fluid-leaks','Fluid leaks','Fugas de líquidos','Buscar manchas, goteos y pérdidas en componentes y debajo del vehículo.'),
  check('air-leaks','Air leaks','Fugas de aire','Escuchar e inspeccionar líneas y conexiones.','brakehose'),
  check('steering-system','Steering system','Sistema de dirección','Seguir y revisar el conjunto completo de dirección.','steering'),
  part('engine-oil','Engine oil / oil level','Aceite del motor / nivel','Varilla, nivel correcto y pérdidas.','oil'),
  part('coolant-level','Coolant / coolant level','Refrigerante / nivel','Marcas del depósito y estado del circuito; no abrir el sistema caliente.','coolant'),
  part('power-steering-fluid','Power steering fluid','Líquido de dirección asistida','Identificar depósito y rango de nivel para el vehículo.'),
  part('steering-drive','Power steering belt / gear','Accionamiento de la dirección asistida','Identificar si el sistema se acciona por correa o engranajes y revisar según fabricante.',undefined,'Según equipo instalado'),
  part('water-pump','Water pump','Bomba de agua','Ubicación, fijaciones, pérdidas y accionamiento instalado.'),
  part('alternator-part','Alternator','Alternador','Fijaciones, terminales y accionamiento.','alternator'),
  part('air-compressor','Air compressor','Compresor de aire','Montaje, líneas y accionamiento del compresor.'),
  part('belts-gears','Belts / gears','Correas / engranajes','Tipo de accionamiento y condición; tensión según especificación.',undefined,'Según equipo instalado'),
  part('engine-hoses','Hoses','Mangueras del motor','Recorrido, condición, abrazaderas y fugas.','coolant'),
 ]},
 {id:'steering-parts',name:'Componentes de dirección',en:'Steering components',items:[
  part('steering-shaft','Steering shaft','Eje de dirección','Eje, juntas y sujeciones sin daño o juego indebido.','steering'),
  part('steering-box','Steering gear box','Caja de dirección','Montaje, tornillos, conexiones y pérdidas.','steering'),
  part('pitman-arm','Pitman arm','Brazo Pitman','Sujeción al eje de salida y unión a la barra.','steering'),
  part('drag-link','Drag link','Barra de arrastre','Barra y articulaciones sin daño o juego indebido.','steering'),
  part('steering-arm','Steering arm','Brazo de dirección','Unión al conjunto de rueda y conexiones.'),
  part('tie-rod','Tie rod','Barra de acoplamiento','Barra transversal, extremos y retenes.','steering'),
  part('steering-knuckle','Steering knuckle','Mangueta de dirección','Integridad del cuerpo, uniones y pivote.'),
  part('spindle','Spindle','Espiga del eje','Reconocer la pieza sobre la que se monta la rueda; no requiere desmontarla para la inspección.'),
  part('steering-reservoir','Power steering reservoir','Depósito de dirección asistida','Depósito, tapa, montaje y marcas de nivel.'),
  part('steering-hoses','Power steering hoses','Mangueras de dirección asistida','Condición, uniones y pérdidas.','steering'),
 ]},
 {id:'steer-axle',name:'Ejes, suspensión y frenos',en:'Axles / suspension / brakes',items:[
  part('tire-part','Tire','Neumático','Presión con manómetro, profundidad, desgaste, laterales y válvula.','tire'),
  part('rim-part','Rim','Rin','Daño, grietas y reparaciones no permitidas.','rim'),
  part('lug-nuts','Lug nuts','Tuercas de rueda','Cantidad, condición y señales de aflojamiento.','rim'),
  part('springs','Springs','Resortes / ballestas','Integridad, alineación y fijación del sistema instalado.','spring'),
  part('leaf-spring','Leaf spring','Hoja de ballesta','Hojas faltantes, rotas o desplazadas.','spring'),
  part('spring-hanger','Spring mounts / hangers','Soportes de suspensión','Soportes, pernos y unión al chasis.','spring'),
  part('spring-shackle','Spring shackle','Gemela de ballesta','Placas, bujes y pernos de la articulación.'),
  part('u-bolts','U-bolts','Abrazaderas en U','Fijación entre eje y suspensión.','spring'),
  part('torque-rod','Torque rod','Barra de reacción','Barra, bujes y anclajes.',undefined,'Según suspensión instalada'),
  part('air-bags','Air bags','Bolsas de aire','Fuelles, montaje y fugas.',undefined,'Según suspensión instalada'),
  part('shock-absorber','Shock absorber','Amortiguador','Montajes, cuerpo y pérdidas.','shock'),
  part('brake-hose','Brake hose / line','Manguera / línea de freno','Condición, recorrido, uniones y fugas.','brakehose'),
  check('brake-leaks','Brake leaks','Fugas de frenos','Buscar o escuchar pérdidas en el circuito y actuadores.','brakehose'),
  part('brake-linings','Brake lining / pads','Revestimientos / pastillas','Condición, desgaste visible y contaminación.','drum','Tambor o disco según equipo'),
  part('brake-drum-disc','Brake drum / disc','Tambor / disco','Integridad, fijación y superficie.','drum','La vista actual representa tambor, no disco'),
  check('brake-contaminants','Brake contaminants','Contaminantes en frenos','Aceite, grasa o residuos sobre superficies de frenado.','drum'),
  part('brake-chamber','Brake chamber','Cámara de freno','Cuerpo, abrazadera, soporte y conexiones.','chamber'),
  part('slack-adjuster','Slack adjuster','Ajustador de freno','Cuerpo, brazo, pasadores y fijaciones.','slack'),
  part('pushrod','Pushrod','Varilla de empuje','Condición, unión y recorrido según el tipo de cámara.','slack'),
 ]},
 {id:'tractor-side',name:'Lado del tractor',en:'Tractor side',items:[
  part('side-lenses','Lenses','Lentes laterales','Presencia, condición y limpieza.','lights'),
  part('side-reflectors','Reflectors','Reflectores laterales','Fijación, limpieza y condición.'),
  part('side-mirrors','Mirrors / cameras','Espejos / cámaras','Montajes, ajuste y funcionamiento.','mirrors','La vista actual incluye espejos, no cámaras'),
  part('battery-part','Battery','Batería','Sujeción, cables, terminales y corrosión.','battery'),
  part('battery-box','Battery box','Caja de baterías','Montaje, estructura y cierre.','battery'),
  part('fuel-tank','Fuel tank','Tanque de combustible','Soportes, bandas y fugas.','fuel'),
  part('fuel-cap','Fuel cap','Tapón de combustible','Presencia, cierre y condición.','fuel'),
  part('def-tank','DEF tank','Tanque DEF','Identificación, montaje, tapón y fugas.'),
  part('tractor-frame','Frame','Chasis del tractor','Largueros, travesaños y uniones.','frame'),
 ]},
 {id:'tractor-trailer',name:'Conexión tractor–remolque',en:'Tractor–trailer coupling',items:[
  part('air-lines','Air lines','Líneas de aire','Condición, recorrido, holgura y ausencia de fugas.','connections'),
  part('gladhands','Glad hands / connectors','Acoples de aire','Asiento, seguros y empaques.','connections'),
  part('electrical-line','Electrical line','Cable eléctrico','Aislamiento, recorrido y holgura.','connections'),
  part('electrical-connector','Electrical connector','Conector eléctrico','Acople correcto y retención.','connections'),
  part('fifth-skid','Fifth wheel skid plate','Placa de quinta rueda','Superficie, garganta, condición y lubricación requerida.','fifth'),
  part('fifth-mount','Fifth wheel platform / mount','Base de quinta rueda','Soportes y fijaciones al chasis.','fifth'),
  part('kingpin-part','Kingpin','Perno rey','Vástago y condición del perno.','kingpin'),
  part('apron','Apron','Delantal del remolque','Superficie de apoyo y condición.','kingpin'),
  check('coupling-gap','Gap','Espacio entre placas','Confirmar contacto correcto, sin separación entre delantal y quinta rueda.','fifth'),
  part('locking-jaws','Locking jaws','Mordazas de cierre','Cierre completo alrededor del vástago del perno.','kingpin'),
  part('release-handle','Release arm / handle','Palanca de liberación','Posición de bloqueo y sujeción.','kingpin'),
  part('safety-latch','Safety latch','Seguro del cierre','Enganche y condición del dispositivo de seguridad.'),
  part('fifth-slide-pins','Sliding fifth wheel locking pins','Pernos de bloqueo de quinta rueda deslizante','Enganche de los pernos y sujeción del mecanismo.',undefined,'Si la quinta rueda es deslizante'),
 ]},
 {id:'trailer-body',name:'Remolque',en:'Trailer',items:[
  part('landing-gear','Landing gear','Patas de apoyo','Montaje, condición y posición de viaje.','landing'),
  part('landing-crank','Landing gear crank / handle','Manivela de patas de apoyo','Condición y retención.','landing'),
  check('landing-clearance','Tractor / landing gear clearance','Espacio libre entre tractor y patas','Verificar espacio suficiente y ausencia de interferencias durante el giro.','landing'),
  part('trailer-frame','Trailer frame','Chasis del remolque','Largueros, travesaños y anclajes.','frame'),
  part('trailer-tape','Reflective tape','Cinta reflectante','Presencia, limpieza y condición.','reflectors'),
 ]},
 {id:'trailer-rear',name:'Parte trasera del remolque',en:'Rear of trailer',items:[
  part('rear-tail-lights','Tail lights','Luces de posición traseras','Estado y encendido.','reflectors'),
  check('rear-brake-lights','Brake lights','Luces de freno traseras','Encendido y apagado al aplicar y liberar frenos.','reflectors'),
  check('rear-turn-signals','Turn signals','Direccionales traseras','Funcionamiento del lado izquierdo y derecho.','reflectors'),
  check('rear-flashers','4-way flashers','Intermitentes traseros de emergencia','Funcionamiento simultáneo.','reflectors'),
  part('rear-markers','Clearance / marker lights','Luces marcadoras traseras','Condición y encendido.','reflectors'),
  part('rear-reflectors','Reflectors','Reflectores traseros','Limpieza, fijación y condición.','reflectors'),
  part('rear-tape','Reflective tape','Cinta reflectante trasera','Presencia, limpieza y condición.'),
 ]},
];
const componentViews:Record<string,string>={"spring-shackle":"shackle","steering-drive":"steeringpump","dash-indicators": "dashboard", "triangles": "triangles", "fuses-breakers": "fuses", "washer": "washer", "heater": "climate", "defroster": "climate", "horn": "horn", "power-steering-fluid": "powerreservoir", "water-pump": "waterpump", "air-compressor": "compressor", "belts-gears": "belts", "steering-shaft": "steeringshaft", "pitman-arm": "pitman", "drag-link": "draglink", "steering-arm": "steeringarm", "tie-rod": "tierod", "steering-knuckle": "knuckle", "spindle": "spindle", "steering-reservoir": "powerreservoir", "steering-hoses": "steeringhoses", "air-bags": "airbags", "torque-rod": "torquerod", "side-reflectors": "sidereflectors", "def-tank": "def", "safety-latch": "safetylatch", "fifth-slide-pins": "slidepins", "rear-tape": "reartape"};
for(const section of inspectionCatalog)for(const item of section.items)if(componentViews[item.id])item.assembly=componentViews[item.id];
export const allInspectionItems=inspectionCatalog.flatMap(section=>section.items);
