'use client';
import {useEffect,useState} from 'react';
import {flushSync} from 'react-dom';
import {Truck,Search,ArrowUpRight,Volume2,ArrowRight,ArrowLeft,Check,RotateCcw,Maximize,Layers,Eye,BookOpen,GraduationCap,Compass,ChevronRight,Box,Info,ShieldCheck,ScanLine,Target,CheckCircle2,Headphones,X,Plus,Minus} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {Progress} from '@/components/ui/progress';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import dynamic from 'next/dynamic';
const TruckView=dynamic(()=>import('./truck-view'),{ssr:false,loading:()=> <div className="cad-loading" role="status"><span className="cad-spinner"/><strong>Preparando tu camión…</strong></div>});
import {parts,zones,sources} from './data';
import {inspectionCatalog,allInspectionItems,targetVehicle} from './inspection-catalog';
export default function Home(){
 const [selected,setSelected]=useState('engine'),[zone,setZone]=useState('all'),[mode,setMode]=useState('explore');
 const [query,setQuery]=useState(''),[xray,setXray]=useState(true),[exploded,setExploded]=useState(false),[isolated,setIsolated]=useState(false),[view,setView]=useState('perspective'),[reset,setReset]=useState(0);
 const [zoom,setZoom]=useState(0),[focus,setFocus]=useState(0);
 const [pickedOpen,setPickedOpen]=useState(false);
 const [pickerOpen,setPickerOpen]=useState(false),[mobileOptions,setMobileOptions]=useState(false);
 const [catalogOpen,setCatalogOpen]=useState(false);
 const [instanceStep,setInstanceStep]=useState(0),[instanceInfo,setInstanceInfo]=useState({label:'',index:0,count:1});
 const [known,setKnown]=useState<string[]>([]),[ready,setReady]=useState(false),[revealed,setRevealed]=useState(false),[sourceOpen,setSourceOpen]=useState(false),[speaking,setSpeaking]=useState(false),[notice,setNotice]=useState('');
 const [quizIndex,setQuizIndex]=useState(0),[quizScore,setQuizScore]=useState(0),[quizDone,setQuizDone]=useState(false);
 const part=parts.find(p=>p.id===selected)!;
 const filtered=parts.filter(p=>(zone==='all'||p.zone===zone)&&`${p.name} ${p.en}`.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').includes(query.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')));
 useEffect(()=>{try{const raw=JSON.parse(localStorage.getItem('cdl-atlas-known')||'[]');if(Array.isArray(raw))setKnown(raw.filter(v=>parts.some(p=>p.id===v)))}catch{}try{const saved=localStorage.getItem('cdl-atlas-last');if(parts.some(p=>p.id===saved))setSelected(saved!);}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('cdl-atlas-known',JSON.stringify(known))}catch{}},[known,ready]);
 useEffect(()=>{if(ready)try{localStorage.setItem('cdl-atlas-last',selected)}catch{}},[selected,ready]);
 useEffect(()=>()=>{if('speechSynthesis'in window)window.speechSynthesis.cancel()},[]);
 function select(id:string){setSelected(id);setRevealed(false);setNotice('');if('speechSynthesis'in window)window.speechSynthesis.cancel();setSpeaking(false);const p=parts.find(p=>p.id===id);if(p&&['engine','brakes','coupling'].includes(p.zone))setXray(true);}
 function changeZone(id:string){setZone(id);setQuery('');setIsolated(false);const p=parts.find(p=>id==='all'||p.zone===id);if(p&&id!=='all')select(p.id);}
 function toggleKnown(){setKnown(v=>v.includes(selected)?v.filter(id=>id!==selected):[...v,selected]);}
 function speak(){if(!('speechSynthesis'in window)){setNotice('Este navegador no ofrece audio. Puedes practicar leyendo el guion.');return;}if(speaking){speechSynthesis.cancel();setSpeaking(false);return;}const u=new SpeechSynthesisUtterance(part.say);u.lang='en-US';u.rate=.82;u.onend=()=>setSpeaking(false);u.onerror=()=>{setSpeaking(false);setNotice('No se pudo reproducir la voz. Inténtalo de nuevo.');};speechSynthesis.cancel();speechSynthesis.speak(u);setSpeaking(true);}
 function changeMode(value:string){setMode(value);setRevealed(false);setQuizDone(false);if(value==='practice'){setZone('all');setQuery('');setQuizIndex(0);setQuizScore(0);select(parts[0].id);setIsolated(true);}else {setIsolated(value==='learn');if(value==='learn'){setZone('all');setQuery('');}}}
 function next(delta=1){if(window.matchMedia('(max-width: 900px)').matches)window.scrollTo({top:0,behavior:'instant'});const index=parts.findIndex(p=>p.id===selected);select(parts[(index+delta+parts.length)%parts.length].id);}
 function grade(correct:boolean){if(window.matchMedia('(max-width: 900px)').matches)window.scrollTo({top:0,behavior:'instant'});const score=quizScore+(correct?1:0);setQuizScore(score);if(correct)setKnown(v=>v.includes(selected)?v:[...v,selected]);if(quizIndex===parts.length-1){setQuizDone(true);return;}const idx=quizIndex+1;setQuizIndex(idx);select(parts[idx].id);}
 useEffect(()=>{
  type Tool={name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown};
  const context=(document as Document & {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const tools:Tool[]=[
   {name:'search_cdl_components',description:'Search the CDL Atlas study components by Spanish or English name.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input!=='object'||!('query'in input)||typeof input.query!=='string')throw new Error('query must be a string');const q=input.query.toLowerCase();return parts.filter(p=>`${p.name} ${p.en}`.toLowerCase().includes(q)).map(({id,name,en,zone})=>({id,name,en,zone}));}},
   {name:'inspect_cdl_component',description:'Open a component in the visible 3D atlas and display its study card.',inputSchema:{type:'object',properties:{id:{type:'string',enum:parts.map(p=>p.id)}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||!('id'in input)||typeof input.id!=='string')throw new Error('id must be a component ID');const p=parts.find(p=>p.id===input.id);if(!p)throw new Error('Unknown component');flushSync(()=>{setMode('explore');setZone(p.zone);setQuery('');setIsolated(true);select(p.id);});return {id:p.id,name:p.name,checks:p.checks,view:'isolated'};}}
  ];
  for(const tool of tools)try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
  return()=>lifecycle.abort();
 },[]);
 const hideAnswer=mode==='practice'&&!revealed;
 return <Tabs value={mode} onValueChange={v=>changeMode(String(v))} className={`app-shell ${mode==='explore'?'truck-only':''}`}>
  <header className="topbar"><a href="/" className="brand"><span className="brand-icon"><Truck size={22}/></span><span>CDL<span className="brand-light">atlas</span><sup>BETA</sup></span></a>
   <div className="mode-tabs"><TabsList><TabsTrigger value="explore"><Compass/>Explorar</TabsTrigger><TabsTrigger value="learn"><BookOpen/>Aprender</TabsTrigger><TabsTrigger value="practice"><GraduationCap/>Practicar</TabsTrigger></TabsList></div>
   <button className="quiet source-button" onClick={()=>setCatalogOpen(true)}><BookOpen size={16}/> Checklist completo</button>
   <button className="quiet source-button" onClick={()=>setSourceOpen(true)}><ShieldCheck size={16}/> Guía y fuentes <ArrowUpRight size={14}/></button>
  </header>
  <TabsContent value={mode} className="workspace">
   <aside className="library"><div className="library-heading"><span className="eyebrow">TU RECORRIDO</span><span className="tiny-pill">CLASE A</span></div><h1>Conoce tu camión.</h1><p className="subtle intro">Una pieza a la vez.</p>
    <label className="search"><Search size={16}/><input aria-label="Buscar piezas en español o inglés" value={query} onChange={e=>{setQuery(e.target.value);if(mode==='practice')changeMode('explore')}} placeholder="Buscar una pieza…"/>{query&&<button aria-label="Borrar búsqueda" onClick={()=>setQuery('')}><X size={13}/></button>}</label>
    <div className="zone-list" aria-label="Filtrar por zona">{zones.map((z,i)=><button disabled={mode==='practice'} key={z.id} className={`zone ${zone===z.id?'active':''}`} onClick={()=>changeZone(z.id)}><span className="zone-number">{i===0?<Box size={16}/>:String(i).padStart(2,'0')}</span><span>{z.name}</span><span className="zone-count">{z.id==='all'?parts.length:parts.filter(p=>p.zone===z.id).length}</span></button>)}</div>
    <div className="part-heading"><span className="eyebrow">{mode==='practice'?'SESIÓN DE PRÁCTICA':'COMPONENTES'}</span><span>{mode==='practice'?`${quizIndex+1} / ${parts.length}`:filtered.length}</span></div>
    <div className="part-list">{mode==='practice'?<p className="practice-help">Observa la pieza resaltada. Di su nombre y explica qué revisarías antes de mostrar la respuesta.</p>:filtered.length?filtered.map(p=><button key={p.id} className={`part-row ${selected===p.id?'selected':''}`} onClick={()=>{select(p.id);setFocus(n=>n+1)}}><span className={`part-dot ${known.includes(p.id)?'done':''}`}>{known.includes(p.id)&&<Check size={10}/>}</span><span>{p.name}<small>{p.en}</small></span><ChevronRight size={13}/></button>):<p className="empty-search">No hay coincidencias en esta zona. Prueba otro término o selecciona “Todo el vehículo”.</p>}</div>
    <div className="progress-card"><div><span>Tu progreso</span><strong>{known.length}<small> / {parts.length}</small></strong></div><Progress value={known.length/parts.length*100} aria-label="Piezas marcadas como aprendidas"/><p>Aprendidas · guardado en este dispositivo</p></div>
   </aside>
   <main className="main-view"><div className="mobile-piece-header"><div><span>Pieza {parts.indexOf(part)+1} de {parts.length} · {known.length} aprendidas</span><h1>{hideAnswer?'¿Qué pieza es?':part.name}</h1>{!hideAnswer&&<p>{part.en}</p>}</div><button aria-label="Buscar o cambiar pieza" onClick={()=>setPickerOpen(true)}><Search size={20}/><span>Piezas</span></button></div><div className="viewer-top"><div><div className="eyebrow">ATLAS INTERACTIVO / PRE-TRIP INSPECTION</div><h2>{mode==='practice'?'Pon a prueba lo que sabes':mode==='learn'?'Tu inspección, paso a paso':'Acércate a cada detalle.'}</h2></div><span className="live-tag"><i/> MODELO CAD</span></div>
    <section className="viewer" aria-label="Explorador del camión"><TruckView selected={selected} zone={zone} xray={xray} exploded={exploded} isolated={isolated} view={view} reset={reset} zoom={zoom} focus={focus} instanceStep={instanceStep} onInstance={(label,index,count)=>setInstanceInfo(prev=>prev.label===label&&prev.index===index&&prev.count===count?prev:{label,index,count})} onSelect={id=>{if(mode!=='practice'){select(id);setPickedOpen(true)}}}/>
     {mode==='explore'&&<><button className="explorer-search" aria-label="Buscar una pieza" onClick={()=>setPickerOpen(true)}><Search size={21}/></button>{pickedOpen&&<div className="explorer-card"><div><strong>{part.name}</strong><span>{part.en}</span></div><button className="explorer-study" onClick={()=>{changeMode('learn');setIsolated(true)}}>Qué revisar <ArrowRight size={17}/></button><button className="explorer-close" aria-label="Cerrar nombre de pieza" onClick={()=>setPickedOpen(false)}><X size={20}/></button></div>}{!pickedOpen&&<div className="explorer-hint">Un dedo: gira · Dos dedos: mueve y acerca<br/><strong>Toca una pieza para conocerla</strong></div>}</>}
     <div className="model-label"><span className="eyebrow">{isolated?"GIRA LA PIEZA CON EL DEDO":"TRACTOR + SEMIRREMOLQUE · 53 FT"}</span><span>{isolated?"Usa + para ver más cerca":"Toca una pieza para acercarte"}</span></div>
     <div className="viewer-tools"><button title="Acercar" aria-label="Acercar" onClick={()=>setZoom(n=>n+1)}><Plus size={18}/></button><button title="Alejar" aria-label="Alejar" onClick={()=>setZoom(n=>n-1)}><Minus size={18}/></button><button className={isolated?'on':''} title="Aislar pieza seleccionada" aria-label="Aislar pieza seleccionada" aria-pressed={isolated} onClick={()=>setIsolated(!isolated)}><ScanLine size={18}/></button><button title="Restablecer vista" aria-label="Restablecer vista" onClick={()=>{setIsolated(false);setXray(true);setPickedOpen(false);setView('perspective');setReset(n=>n+1)}}><RotateCcw size={18}/></button><button title="Acercar a la pieza" aria-label="Acercar a la pieza" onClick={()=>setFocus(n=>n+1)}><Maximize size={18}/></button></div>
     {isolated&&mode!=='practice'&&<div className="instance-controls"><span>{instanceInfo.label}</span>{instanceInfo.count>1&&<button onClick={()=>setInstanceStep(n=>n+1)}>Otro ejemplar {instanceInfo.index+1}/{instanceInfo.count} <ArrowRight size={12}/></button>}</div>}
     <div className="selection-label"><span className="selection-dot"/>{hideAnswer?'Identifica la pieza resaltada':part.en}<span>{hideAnswer?'?':String(parts.indexOf(part)+1).padStart(2,'0')}</span></div>
     <div className="viewer-bottom"><span><Compass size={14}/> Arrastra para girar <b>·</b> Zoom: + / −, rueda o pellizco</span><div className="view-buttons">{[['perspective','3D'],['left','Lateral'],['front','Frente'],['rear','Atrás'],['top','Arriba']].map(([v,label])=><button key={v} onClick={()=>setView(v)} className={view===v?'active':''}>{label}</button>)}</div></div>
    </section>
    <div className={`model-controls ${mobileOptions?'options-open':''}`}><button className="detail-toggle" aria-pressed={isolated} onClick={()=>{setIsolated(!isolated);setView('perspective')}}>{isolated?<Truck size={16}/>:<ScanLine size={16}/>} {isolated?"Ver camión completo":"Ver pieza en detalle"}</button><button className="mobile-options" aria-expanded={mobileOptions} onClick={()=>setMobileOptions(v=>!v)}>Más opciones</button><div className="advanced-controls"><Layers size={17}/><label>Ver interior <Switch disabled={isolated} checked={xray} onCheckedChange={setXray} aria-label="Ver componentes internos"/></label><span className="control-separator"/><label>Separar piezas <Switch disabled={isolated} checked={exploded} onCheckedChange={setExploded} aria-label="Separar piezas del modelo"/></label></div><span className="model-note">{isolated?'Gira la pieza para observar sus conexiones y fijaciones.':exploded?'Separación ilustrativa; no es una posición de inspección.':'Selecciona una pieza del modelo o de la lista.'}</span></div>
    <div className="learning-strip"><span className="strip-icon"><Target size={21}/></span><div><strong>{mode==='practice'?'Reconocer es el primer paso. Explicarlo es el siguiente.':'No memorices solo palabras. Aprende dónde mirar.'}</strong><p>{mode==='practice'?'Esta práctica es autoevaluación; no califica tu voz ni equivale al examen oficial.':'Encuentra la pieza, entiende qué revisar y practica cómo decirlo en inglés.'}</p></div><span className="strip-index">{mode==='practice'?`${quizIndex+1}/${parts.length}`:`01 — ${parts.length}`}</span></div>
   </main>
   <aside className="detail-panel" aria-label="Ficha de la pieza seleccionada">
    {quizDone?<div className="quiz-result"><CheckCircle2 size={48}/><span className="eyebrow">RECORRIDO COMPLETADO</span><h2>{quizScore} de {parts.length}</h2><p>piezas que indicaste recordar. Repite las que necesitan otro repaso.</p><button className="primary" onClick={()=>changeMode('practice')}>Practicar otra vez <RotateCcw size={16}/></button><button className="secondary" onClick={()=>changeMode('explore')}>Volver al atlas</button></div>:<>
    <div className="detail-kicker"><span className="eyebrow">{mode==='practice'?'AUTOEVALUACIÓN':zones.find(z=>z.id===part.zone)?.name}</span><span className="detail-number">{String(parts.indexOf(part)+1).padStart(2,'0')}</span></div>
    <h2>{hideAnswer?'¿Qué pieza es?':part.name}</h2><p className="english-name">{hideAnswer?'¿Dónde está y qué inspeccionarías?':part.en}</p>
    {hideAnswer?<div className="recall-card"><GraduationCap size={36}/><h3>Inténtalo sin ayuda.</h3><p>1. Nombra la pieza.<br/>2. Explica su función.<br/>3. Di qué defectos buscarías.</p><button className="primary" onClick={()=>setRevealed(true)}><Eye size={17}/> Mostrar respuesta</button></div>:<>
    <p className="purpose">{part.purpose}</p><div className="section-label"><CheckCircle2 size={15}/> QUÉ REVISAR</div><ul className="check-list">{part.checks.map((c,i)=><li key={c}><span>{i+1}</span>{c}</li>)}</ul>
    <div className="say-card"><div><span className="eyebrow">ASÍ PUEDES DECIRLO</span><button onClick={speak} aria-label={speaking?'Detener audio':'Escuchar guion en inglés'}><Volume2 size={16}/>{speaking?'Detener':'Escuchar'}</button></div><blockquote lang="en">“{part.say}”</blockquote><span className="audio-caption"><Headphones size={12}/> Inglés · ejemplo para practicar</span></div>
    <div className="tip"><Info size={16}/><p>{part.tip}</p></div>
    {notice&&<p className="notice" role="status">{notice}</p>}
    {mode==='practice'?<div className="grade-actions"><p>¿Pudiste identificarla y explicar los puntos?</p><button className="primary" onClick={()=>grade(true)}>Sí, lo recordé <Check size={16}/></button><button className="secondary" onClick={()=>grade(false)}>Necesito repasarla <ArrowRight size={16}/></button></div>:<button className={`primary learned ${known.includes(selected)?'is-known':''}`} onClick={toggleKnown}>{known.includes(selected)?'Marcada como aprendida':'Marcar como aprendida'} <Check size={17}/></button>}
    </>}
    {mode!=='practice'&&<div className="detail-nav"><button onClick={()=>next(-1)} aria-label="Pieza anterior"><ArrowLeft size={17}/></button><span>{parts.indexOf(part)+1} de {parts.length} componentes</span><button onClick={()=>next()} aria-label="Siguiente pieza"><ArrowRight size={17}/></button></div>}
    </>}
   </aside>
  </TabsContent>
  {mode!=='practice'&&<div className="mobile-continue"><button className="mobile-back" aria-label="Pieza anterior" onClick={()=>next(-1)}><ArrowLeft size={20}/></button><button className="primary" onClick={()=>{setKnown(v=>v.includes(selected)?v:[...v,selected]);next();setIsolated(true)}}>Ya la sé · Siguiente <ArrowRight size={20}/></button></div>}
  <Dialog open={pickerOpen} onOpenChange={setPickerOpen}><DialogContent className="piece-picker"><DialogTitle>¿Qué quieres revisar?</DialogTitle><DialogDescription>Elige una pieza para verla de cerca.</DialogDescription><label className="search"><Search size={20}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar en español o inglés" aria-label="Buscar una pieza"/></label><div className="picker-zones">{zones.map(z=><button key={z.id} aria-pressed={zone===z.id} onClick={()=>setZone(z.id)}>{z.name}</button>)}</div><div className="picker-list">{filtered.map(p=><button key={p.id} onClick={()=>{if(mode==='practice')changeMode('learn');select(p.id);setIsolated(mode!=='explore');setPickedOpen(true);setFocus(n=>n+1);setPickerOpen(false);window.scrollTo({top:0,behavior:'instant'})}}><span>{p.name}<small>{p.en}</small></span>{known.includes(p.id)?<CheckCircle2 size={20}/>:<ChevronRight size={20}/>}</button>)}{!filtered.length&&<p>No encontramos esa pieza. <button onClick={()=>{setQuery('');setZone('all')}}>Ver todas</button></p>}</div><button className="secondary" onClick={()=>{setPickerOpen(false);setCatalogOpen(true)}}><BookOpen size={18}/> Checklist completo</button></DialogContent></Dialog>
  <footer><span><ShieldCheck size={13}/> Herramienta de estudio · reconstrucción de referencia para clase A</span><button onClick={()=>setSourceOpen(true)}>Alcance, frenos de aire y fuentes <ArrowUpRight size={12}/></button><span>Aprende con intención.</span></footer>
  <Dialog open={catalogOpen} onOpenChange={setCatalogOpen}><DialogContent className="catalog-dialog"><DialogTitle>Checklist completo · Class A</DialogTitle><DialogDescription>{allInspectionItems.length} elementos en las 9 zonas solicitadas. Nombra, señala y explica cada revisión.</DialogDescription><div className="catalog-target"><strong>Objetivo: {targetVehicle.tractor} · {targetVehicle.engine} · 53 pies</strong><p>{targetVehicle.description}</p></div><p className="catalog-scope">Las vistas disponibles muestran conjuntos de referencia. Cada pieza física del checklist tiene una vista de referencia, individual o de conjunto. Las pruebas de funcionamiento no se simulan y las piezas aún no tienen verificación dimensional 1:1.</p>{inspectionCatalog.map((section,index)=><section className="catalog-section" key={section.id}><h3><span>{String(index+1).padStart(2,'0')}</span>{section.name}<small>{section.items.length}</small></h3><div>{section.items.map(item=><article key={item.id} className="catalog-row"><div><strong>{item.es}</strong><span lang="en">{item.en}</span><p>{item.focus}</p>{item.conditional&&<em>{item.conditional}</em>}</div>{item.assembly?<button onClick={()=>{select(item.assembly!);setIsolated(true);setMode('explore');setCatalogOpen(false)}}>Ver conjunto <ArrowUpRight size={12}/></button>:<span className="coverage-pending">{item.kind==='procedure'?'Demostración pendiente':item.kind==='check'?'Revisión sin simulación':'Sin vista 3D'}</span>}</article>)}</div></section>)}</DialogContent></Dialog>
  <Dialog open={sourceOpen} onOpenChange={setSourceOpen}><DialogContent className="source-dialog"><DialogTitle>Una base para estudiar con criterio.</DialogTitle><DialogDescription>CDL Atlas · alcance del modelo de referencia</DialogDescription><div className="source-content"><p>Explora {parts.length} fichas de un tractocamión con semirremolque, en español y con guiones originales en inglés. El visor carga una representación web derivada del ensamblaje CAD de 8.857 sólidos. El modelo de referencia de Cascadia y DD15 contiene piezas detalladas: perfiles de neumáticos y rines, carcasas, soportes, pasadores, mangueras y conexiones. No es un escaneo ni CAD oficial de un fabricante; las ubicaciones y equipos varían entre vehículos.</p><h3>Antes de preparar tu examen</h3><p>Consulta el manual vigente de tu estado, el formato de prueba y el vehículo de tu escuela. Esta versión no ofrece un temario completo para todos los estados, clases B/C, autobuses o sistemas hidráulicos.</p><h3>Frenos de aire y revisión en cabina</h3><p>Las fichas muestran componentes; no reemplazan la demostración de frenos. Debes aprender con tu instructor la preparación segura del vehículo, la verificación del gobernador, la pérdida de presión, la advertencia de baja presión y la actuación de emergencia, con los valores y pasos de tu vehículo y examen.</p><p>También se requiere practicar los frenos de estacionamiento y servicio y los controles de cabina, incluyendo cinturón, limpiaparabrisas, desempañador y bocina. No se simulan en esta versión.</p><h3>Referencias mecánicas del modelo</h3><p>Las formas se reconstruyeron observando documentación e imágenes de actuadores y ajustadores Bendix, motor Detroit DD15 y quintas ruedas SAF-HOLLAND. No se han copiado sus modelos CAD ni sus fotografías. Los nombres de fabricantes identifican las referencias, no una afiliación o certificación.</p><h3>Referencias</h3>{sources.map(s=><a className="source-link" href={s.url} key={s.url} target="_blank" rel="noreferrer"><strong>{s.title} <ArrowUpRight size={14}/></strong><span>{s.note}</span></a>)}<p className="subtle">Revisión de referencias: 5 de septiembre de 2026. Sin afiliación al DMV o a FMCSA. Tu progreso se guarda únicamente en este navegador. El audio utiliza las voces disponibles en tu dispositivo.</p></div></DialogContent></Dialog>
 </Tabs>
}
