'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,CheckCircle2,Volume2} from 'lucide-react';
import {questions,categories,startExam,sourceFor,startSession,answerSession,nextQuestion,missedIds,readSession,readHistory,type Session,type History} from './quiz';
export default function Exams(){
 const [session,setSession]=useState<Session|null>(null),[history,setHistory]=useState<History>({}),[ready,setReady]=useState(false),[english,setEnglish]=useState(false),[notice,setNotice]=useState(''),[playing,setPlaying]=useState(false);
 const audioToken=useRef(0),heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('cdl-atlas-exams-v1')||'{}');setSession(readSession(saved.session));setHistory(readHistory(saved.history));}catch{}setReady(true)},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem('cdl-atlas-exams-v1',JSON.stringify({session,history}))}catch{setNotice('No se pudo guardar el avance. Puedes continuar esta sesión.')}},[session,history,ready]);
 function stop(){audioToken.current++;if('speechSynthesis'in window)window.speechSynthesis.cancel();setPlaying(false)}
 useEffect(()=>{stop();heading.current?.focus();window.scrollTo({top:0,behavior:'instant'});return()=>{audioToken.current++;if('speechSynthesis'in window)window.speechSynthesis.cancel()}},[session?.index,session?.title]);
 function speak(text:string,lang:string){
  if(!('speechSynthesis'in window)){setNotice('Audio no disponible en este navegador. Puedes leer todo en pantalla.');return;}
  const wasPlaying=playing;stop();if(wasPlaying)return;
  const token=audioToken.current,u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=lang==='en-US'?.7:.9;
  const voice=window.speechSynthesis.getVoices().find(v=>v.lang.startsWith(lang.slice(0,2)));if(voice)u.voice=voice;
  u.onend=()=>{if(token===audioToken.current)setPlaying(false)};u.onerror=()=>{if(token===audioToken.current){setPlaying(false);setNotice('No se pudo reproducir el audio. Inténtalo otra vez.')}};
  setPlaying(true);window.speechSynthesis.speak(u);
 }
 function beginExam(){stop();setNotice('');setSession(startExam())}
 function begin(ids:string[],title:string){stop();setNotice('');setSession(startSession(ids,title))}
 const errors=questions.filter(q=>history[q.id]===false).map(q=>q.id);
 const done=session!==null&&session.index===session.items.length;
 const item=session&&!done?session.items[session.index]:null;
 const question=item?questions.find(q=>q.id===item.id)!:null;
 const answer=session&&!done?session.answers[session.index]:null;
 const isExam=session?.mode==='exam';
 const showFeedback=answer!==null&&!isExam;
 function choose(choice:number){if(!session||!question||(!isExam&&answer!==null))return;stop();setSession(answerSession(session,choice));if(!isExam)setHistory(prev=>({...prev,[question.id]:choice===question.correct}))}
 function advance(){if(!session||!question||answer===null)return;stop();if(isExam)setHistory(prev=>({...prev,[question.id]:answer===question.correct}));setSession(nextQuestion(session))}
 const misses=session?missedIds(session):[];
 return <main className="exams-page">
  <header className="exams-header"><a href="/" aria-label="Volver al camión"><ArrowLeft size={19}/> Camión 3D</a><span>CDLatlas · Exámenes</span></header>
  {!ready?<p role="status">Cargando tu avance…</p>:!session?<>
   <span className="eyebrow">APRENDE EN TU IDIOMA</span><h1 ref={heading} tabIndex={-1}>Vamos por tu CDL.</h1><p className="exam-intro">Entiende la respuesta en español. Practica también cómo se pregunta en inglés.</p>
   <div className="exam-mode-grid"><section className="exam-mode-card"><span className="eyebrow">MODO ESTUDIO</span><h2>Aprende a tu ritmo</h2><strong>{questions.length} preguntas disponibles</strong><p>Explicación después de cada respuesta. Estudia todo el banco o elige un tema abajo.</p><button className="secondary" onClick={()=>begin(questions.map(q=>q.id),'Banco completo · todos los temas')}>Estudiar todo el banco <ArrowRight size={18}/></button></section><section className="exam-mode-card exam-mode-featured"><span className="eyebrow">MODO EXAMEN</span><h2>Ponte a prueba</h2><strong>50 preguntas · conocimientos generales</strong><p>Preguntas al azar, sin repetir. Tu resultado y las explicaciones aparecen al terminar.</p><button className="primary" onClick={beginExam}>Comenzar examen de 50 <ArrowRight size={18}/></button><small>Simulacro de práctica sin límite de tiempo.</small></section></div>
   <div className="exam-progress"><strong>{Object.keys(history).length} de {questions.length} preguntas practicadas</strong><span>Guardado en este dispositivo</span>{errors.length>0&&<button onClick={()=>begin(errors,'Repasar mis errores')}>Repasar mis {errors.length} errores <ArrowRight size={18}/></button>}</div>
   <h2>Estudia por tema · Class A</h2><p>Conocimientos generales, frenos de aire y combinación tractor–remolque.</p>
   <div className="exam-grid">{categories.filter(c=>c.core).map(c=><button className="exam-topic" key={c.id} onClick={()=>begin(questions.filter(q=>q.category===c.id).map(q=>q.id),c.name)}><BookOpen size={23}/><strong>{c.name}</strong><span lang="en">{c.en}</span><small>{questions.filter(q=>q.category===c.id).length} preguntas · {questions.filter(q=>q.category===c.id&&history[q.id]===true).length} correctas en tu último intento por pregunta</small><b>Practicar <ArrowRight size={17}/></b></button>)}</div>
   <h2>Especialidades</h2><p>Elige las que correspondan al vehículo y al trabajo que buscas.</p>
   <div className="exam-grid">{categories.filter(c=>!c.core).map(c=><button className="exam-topic" key={c.id} onClick={()=>begin(questions.filter(q=>q.category===c.id).map(q=>q.id),c.name)}><strong>{c.name}</strong><span lang="en">{c.en}</span><small>{questions.filter(q=>q.category===c.id).length} preguntas</small><b>Practicar <ArrowRight size={17}/></b></button>)}</div>
   <details className="exam-sources"><summary>Alcance y manuales oficiales</summary><p>Banco inicial de {questions.length} preguntas originales de práctica. No es el banco oficial ni cubre todo el temario. El resultado no equivale a aprobar el examen. Confirma requisitos, idioma y manual vigente con el DMV de tu estado.</p><p>Base común: manual comercial de Oregon, secciones indicadas en cada respuesta. Referencias revisadas el 6 de septiembre de 2026. El simulacro toma 50 de las 60 preguntas de conocimientos generales; no mezcla especialidades. Frenos de aire es un tema de examen relacionado con restricciones, no un endorsement independiente. La habilitación X combina tanque y materiales peligrosos; aquí se estudian por separado. Pasajeros y autobús escolar también pueden requerir pruebas prácticas y otros requisitos.</p><a href={sourceFor('3')} target="_blank" rel="noreferrer">Transporte seguro de carga · Manual §3</a>{categories.map(c=><a href={c.source} target="_blank" rel="noreferrer" key={c.id}>{c.name} · Manual §{c.section}</a>)}</details>
  </>:done?<section className="exam-result"><CheckCircle2 size={46}/><span className="eyebrow">{isExam?'EXAMEN TERMINADO':'PRÁCTICA COMPLETADA'}</span><h1 ref={heading} tabIndex={-1}>{session.items.length-misses.length} de {session.items.length}</h1><p>respuestas correctas en esta sesión de {session.title.toLowerCase()}.</p><p>{misses.length?'Repasa tus errores para entender qué te faltó.':'¡Bien! Continúa con otro tema y con el manual de tu estado.'}</p>{misses.length>0&&<button className="primary" onClick={()=>begin(misses,'Repaso de esta sesión')}>Repasar {misses.length} errores</button>}<button className="secondary" onClick={()=>{stop();setSession(null)}}>Elegir otro tema</button>{isExam&&<button className="secondary" onClick={beginExam}>Hacer otro examen de 50</button>}<small>Este resultado es de práctica, no una calificación oficial.</small><div className="exam-review"><h2>Revisa tus respuestas</h2>{session.items.map((entry,i)=>{const q=questions.find(q=>q.id===entry.id)!;const correct=session.answers[i]===q.correct;return <details key={entry.id}><summary><span>{correct?'✓':'✕'} {i+1}. {q.prompt.es}</span></summary><p><strong>Tu respuesta:</strong> {q.options[session.answers[i]!].es}</p>{!correct&&<p><strong>Correcta:</strong> {q.options[q.correct].es}</p>}<p>{q.why}</p><a href={sourceFor(q.section)} target="_blank" rel="noreferrer">Manual oficial · §{q.section}</a></details>})}</div></section>:question&&item&&session?<section className="exam-question">
   <button className="exam-back" onClick={()=>{stop();setSession(null)}}><ArrowLeft size={17}/> Temas</button><div className="exam-question-meta"><span>{isExam?'Modo examen · ':'Estudio · '}{session.title}</span><strong>{session.index+1} / {session.items.length}</strong></div><progress value={session.index} max={session.items.length} aria-label="Avance de esta sesión"/>
   <h1 ref={heading} tabIndex={-1}>{question.prompt.es}</h1><label className="exam-language"><input type="checkbox" checked={english} onChange={e=>setEnglish(e.target.checked)}/> Mostrar también en inglés</label>{english&&<p className="exam-english" lang="en">{question.prompt.en}</p>}
   <div className="exam-audio"><button onClick={()=>speak([question.prompt.es,...item.order.map((n,i)=>`${String.fromCharCode(65+i)}. ${question.options[n].es}`)].join(' '),'es-MX')}><Volume2 size={17}/>{playing?'Detener audio':'Escuchar en español'}</button>{english&&<button onClick={()=>speak([question.prompt.en,...item.order.map((n,i)=>`${String.fromCharCode(65+i)}. ${question.options[n].en}`)].join(' '),'en-US')}><Volume2 size={17}/> Inglés lento</button>}</div>
   <div className="exam-answers">{item.order.map((n,i)=><button key={n} disabled={!isExam&&answer!==null} aria-pressed={answer===n} onClick={()=>choose(n)} className={isExam?(answer===n?'chosen':''):showFeedback&&n===question.correct?'correct':answer===n?'incorrect':''}><span className="answer-letter">{String.fromCharCode(65+i)}</span><span>{question.options[n].es}{english&&<small lang="en">{question.options[n].en}</small>}{showFeedback&&n===question.correct&&<b>Respuesta correcta</b>}{showFeedback&&answer===n&&n!==question.correct&&<b>Tu respuesta</b>}</span></button>)}</div>
   {showFeedback&&<div className="exam-feedback" role="status"><h2>{answer===question.correct?'¡Correcto!':'Vamos a entenderlo.'}</h2><p>{question.why}</p><button className="exam-back" onClick={()=>speak(question.why,'es-MX')}><Volume2 size={17}/> Escuchar explicación</button><a href={sourceFor(question.section)} target="_blank" rel="noreferrer">Ver manual oficial · §{question.section}</a><button className="primary" onClick={advance}>{session.index+1===session.items.length?'Ver mi resultado':'Siguiente pregunta'} <ArrowRight size={18}/></button></div>}
   {isExam&&<div className="exam-next"><p>Elige una respuesta. Puedes cambiarla antes de continuar.</p><button className="primary" disabled={answer===null} onClick={advance}>{session.index+1===session.items.length?'Terminar y ver resultado':'Siguiente pregunta'} <ArrowRight size={18}/></button></div>}
  </section>:null}
  {notice&&<p className="exam-notice" role="status">{notice}</p>}
 </main>;
}
